### ISSUE TITLE
Upgrading to 2.2.2 causes our tests to not run

### ISSUE THREAD

**Issue by danwenzel** [ember-cli/ember-cli-qunit#147] opened 2016-09-13 19:27 UTC
If we update our version of ember-cli-qunit to 2.2.2, none of our tests run.   

2.2.1 works fine.

Here's what we're getting:

`No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.`

Running `ember test --server` I get this error in the terminal:

`Browser "phantomjs /Users/dwenzel/Workspace/web-ui/node_modules/testem/assets/phantom.js http://localhost:4201/406/tests/index.html?coverage&hidepassed" failed to connect. testem.js not loaded?`

Unfortunately I don't see much more helpful info...

**Comment by nathanhammond** [comment] 2016-09-13 20:33
It seems very unlikely that 2.2.1 => 2.2.2 is causing this problem. Is it possible that you're changing more than just `ember-cli-qunit`?

[This is the extent of the changes between versions.](https://github.com/ember-cli/ember-cli-qunit/compare/v2.2.1...v2.2.2#diff-bdd4ec6f7af4d2be23cdc0207abd615d)

We need more information in order to be able to debug. Can you come up with a reproduction that you can share with us? If not you're unfortunately on your own.

**Comment by rtwall** [comment] 2016-09-13 21:21
I ran into the same issue with PhantomJS and reverting it back to 2.2.1 fixed the problem.

Remote debugging PhantomJS locked up as well. 

End of PhantomJS output:
```
2016-09-13T21:04:56 [DEBUG] Phantom - execute: Script & Arguments
2016-09-13T21:04:56 [DEBUG]      script: "/usr/src/app/node_modules/testem/assets/phantom.js"
2016-09-13T21:04:56 [DEBUG]      0 arg: "http://localhost:7357/9768/tests/index.html?hidepassed&coverage=true"
2016-09-13T21:04:56 [DEBUG] Phantom - execute: Starting normal mode
2016-09-13T21:04:56 [DEBUG] WebPage - setupFrame ""
2016-09-13T21:04:56 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2016-09-13T21:04:56 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2016-09-13T21:04:56 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 10
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 50
2016-09-13T21:05:37 [DEBUG] WebPage - setupFrame ""
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 51
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 53
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 56
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 58
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 61
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 63
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 66
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 69
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 71
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 74
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 76
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 79
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 81
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 84
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 86
2016-09-13T21:05:37 [DEBUG] WebPage - setupFrame "<!--framePath //<!--frame0-->-->"
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 87
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 88
2016-09-13T21:05:37 [DEBUG] WebPage - updateLoadingProgress: 100
2016-09-13T21:05:37 [DEBUG] WebPage - setupFrame ""
2016-09-13T21:05:37 [DEBUG] CookieJar - Saved "io=uN_nQWNORAVsPfeeAAAD; domain=localhost; path=/socket.io/"
2016-09-13T21:05:38 [DEBUG] CookieJar - Saved "io=uN_nQWNORAVsPfeeAAAD; domain=localhost; path=/socket.io/"
```

**Comment by rwjblue** [comment] 2016-09-13 21:25
I can't grok why moving that up would cause this failure. 

What versions of Phantom?

**Comment by rtwall** [comment] 2016-09-13 21:26
```
>phantomjs --version
2.1.1
```

**Comment by danwenzel** [comment] 2016-09-13 21:26
My version of PhantomJS is 2.0.0

**Comment by thomblake** [comment] 2016-09-13 21:34
Maybe something to do with our autostart setting or a related race condition? I don't think we've done much configuration... (I'm with @danwenzel)

**Comment by danwenzel** [comment] 2016-09-13 21:36
Ah yes.  Setting `autostart:false` in `tests/blanket-options.js` fixes it

**Comment by danwenzel** [comment] 2016-09-13 21:40
```
$ npm list ember-cli-blanket
└── ember-cli-blanket@0.9.9
```

**Comment by denchen** [comment] 2016-09-13 23:32
I was pulling my hair out today wondering why my tests were suddenly not running after a fresh npm/bower install. Thanks for the "fix", @danwenzel !

But can you or someone explain to me what this setting does and WHY this fixes the problem?

**Comment by thomblake** [comment] 2016-09-13 23:37
Yeah that's what we'd like to know too

**Comment by nathanhammond** [comment] 2016-09-14 05:02
Okay, so this is likely a bug in ember-cli-blanket, gimme a bit to investigate.

**Comment by nathanhammond** [comment] 2016-09-14 05:29
Confirmed, is an issue, this change does cause the problem. Note that this change was to also get around the duplicate `Qunit.start()` calls because of changes to jQuery's `ready` behavior in 3.X. So, interplay of `ember-cli-blanket` with this is broken.

Hey @sglanzer! The fix here is for `ember-cli-blanket` to hook [`ember-cli-test-loader`](https://github.com/ember-cli/ember-cli-test-loader) to insert its module instrumentation. That's the ideal insertion point for what you're trying to accomplish. This also has the benefit of reducing the number of intimate and private APIs inside of Ember's module loading infrastructure that it needs to touch. Also it no longer has to support `autostart` as a feature since modules will be instrumented as part of the same loading step that Ember normally uses.

For those following along at home I'm closing this issue here as it will need to be addressed in the addon. I'll also copy this into a new issue in the addon.

**Closed by nathanhammond** 2016-09-14 05:29 UTC

**Comment by danwenzel** [comment] 2016-09-14 13:22
Thanks, @nathanhammond!  I'll keep an eye on that issue.
