### ISSUE TITLE
Unregister/register service not working in beforeEach

### ISSUE THREAD

**Issue by erichonkanen** [ember-cli/ember-cli-qunit#203] opened 2018-02-06 01:35 UTC
Using the latest with new test style and attempting to stub out an existing service with a mock one for my acceptance/other tests doing the following:
`ember-cli-qunit@4.2.1`
`ember-source@3.0.0-beta.3`
```
const setupLocalAcceptanceTest = function(hooks) {
  hooks.beforeEach(function() {
    this.owner.unregister('service:stream');
    this.owner.register('service:stream', STREAM_STUB);
```
```
module('Acceptance | test/stream-mixin', (hooks) => {
  setupApplicationTest(hooks);
  setupLocalAcceptanceTest(hooks);
```
This does not work and in my test the real service is used. Am I missing something or should this work? Also tried injecting the mock service as `this.owner.inject('route', 'stream', 'service:stub-stream')` which didn't work either. Ideally I can replace it via the registration method.

**Comment by rwjblue** [comment] 2018-02-11 16:57
Can you provide a demo repo so we can try to help figure this out? Generally speaking, this type of thing is known to work...

**Comment by erichonkanen** [comment] 2018-02-12 05:56
will get to it this week, started playing with ember twiddle

**Comment by rwjblue** [comment] 2018-02-16 15:11
I suspect the issue is that _something_ eagerly looks up the `service:stream` in an instance-initializer. If this is the case, there is no way to register a stub (because the instance-initializers are ran before any user-land hooks in the new testing system).

**Comment by erichonkanen** [comment] 2018-02-16 17:16
I just checked and I only have 1 instance initializer which is for a mirage workaround... I do have an initializer for the stream service:
```
export function initialize(application) {
  application.inject('component', 'stream', 'service:stream');
  application.inject('controller', 'stream', 'service:stream');
  application.inject('route', 'stream', 'service:stream');
}

export default {
  name: 'stream',
  initialize,
};
```
and also it is used right away in the app route

**Comment by rwjblue** [comment] 2018-02-16 20:11
Hmm, an initializer like this seems fine generally speaking. But anything that forces the service:stream to exist eagerly (the main place this can happen is via an instance-initializer) will mean that you cannot stub it. For example, if you have any instance-initializers that look up routes, controllers, or components eagerly you will be unable to stub `service:stream`. 

One example that I ran into earlier this week is that ember-simple-auth adds an instance-initializer that looks up `route:application`, which would cause exactly the issues you are seeing.

**Comment by erichonkanen** [comment] 2018-02-16 20:28
interesting, we are using ember-simple-auth.. how could I check if that was the cause? I'll be honest I was able to get around it by doing this less ideal solution:
```  hooks.beforeEach(function() {
    // mock the stream service methods -- could not get straight up unregister/
    // register to replace the original for some reason so stubbed the methods
    // instead for now -- revisit later -- 2/10/2018.
    this.owner.lookup('service:stream').setProperties({
      connect() { return RSVP.resolve(); },
      disconnect() { return RSVP.resolve(); },
      getConnection() { return RSVP.resolve(); },
      reconnect() { return RSVP.resolve(); },
      register() {},
      subscribe() { return RSVP.resolve(); },
      unregister() {},
      unsubscribe() { return RSVP.resolve(); },
    });
```

**Comment by erichonkanen** [comment] 2018-02-21 07:01
just ran into same problem on same app when adding an integration test helper that mocks out services: ```export function setupIntegrationTest(hooks) {
  hooks.beforeEach(function() {
    this.owner.register('service:logger', Service.extend(STUB_BASE.logger));
    this.owner.register('service:store', Service.extend(STUB_BASE.store));
    this.owner.register('service:stream', Service.extend(STUB_BASE.stream));
    this.owner.register('service:user', Service.extend(STUB_BASE.currentUser));
    this.logger = this.owner.lookup('service:logger');
    this.store = this.owner.lookup('service:store');
    this.stream = this.owner.lookup('service:stream');
    this.user = this.owner.lookup('service:user');
```
```module('Integration | Component | to-elsewhere/modals/foo', (hooks) => {
  setupRenderingTest(hooks);
  setupIntegrationTest(hooks);
```

**Comment by tpetrone** [comment] 2018-05-10 21:38
So that would make impossible to stub `store service`?

**Comment by rajneeshnagarro** [comment] 2018-05-30 07:11
Can you try the following?

```
test('my test', function(assert) {
    const owner = Ember.getOwner(this);
    // Your code with owner to get the service
    owner.lookup(‘service:stream’)
}); 

```

**Comment by GreatWizard** [comment] 2018-06-11 17:12
I run into the same issue on 3.1.

@rajneeshnagarro owner is undefined: `Cannot read property 'lookup' of undefined`

**Comment by chrisvdp** [comment] 2018-06-14 20:10
I am having the same issue and I also get `Cannot read property 'lookup' of undefined` when running the example in @rajneeshnagarro example using Ember 3.0

**Comment by Bushjumper** [comment] 2018-08-22 06:00
I also ran into this issue when attempting to mock `service:store` in a unit test. 

Using unregister inside `Ember.run` seems to get around it for now:

```
  hooks.beforeEach(function() {
    run(() => {
      this.owner.unregister('service:store');
      this.owner.register('service:store', MockStore);

      this.mockstore = this.owner.lookup('service:store');
    });
  });

```

**Comment by tmquinn** [comment] 2018-09-26 20:43
So I have run into this issue as well but it's only until @Bushjumper's comment. unregister does run loop stuff, is the intention that we use the runloop here?

Also, do I need to unregister something, in order to register it?

**Comment by nicksteffens** [comment] 2019-04-03 21:15
Still seeing this issue when mocking the service:router inside integrations tests.

**Comment by tschoartschi** [comment] 2019-04-04 13:42
We also encountered this issue. Would be nice to use `beforeEach` because it would make our testing code smaller :-)

**Comment by rwjblue** [comment] 2019-04-04 14:24
> Still seeing this issue when mocking the service:router inside integrations tests.

Don't do that 😈. Seriously though, why would you want to mock the router?

**Comment by rwjblue** [comment] 2019-04-04 14:26
FWIW, I'm going to close this issue:

* ember-cli-qunit is deprecated
* the issue is fairly well known/understood

I'd totally be open to making an issue on emberjs/ember-test-helpers to warn/assert when someone attempts to register something that has already been instantiated. That would at least remove the WAT factor of "why isn't my fake service being used"...

**Closed by rwjblue** 2019-04-04 14:26 UTC

**Comment by bartocc** [comment] 2019-06-28 08:50
> I'd totally be open to making an issue on emberjs/ember-test-helpers to warn/assert when someone attempts to register something that has already been instantiated. That would at least remove the WAT factor of "why isn't my fake service being used"...

@rwjblue I've created https://github.com/emberjs/ember-test-helpers/issues/672 to implement a `warn/assert` as you suggested

> > Still seeing this issue when mocking the service:router inside integrations tests.
> 
> Don't do that 😈. Seriously though, why would you want to mock the router?

As for ☝️, my use case is quite simple: I want my component to be aware of the router's `currentRouteName`. I don't really see why this would be a bad practice, but maybe you can enlighten me 🤩

**Comment by rwjblue** [comment] 2019-06-28 13:32
Just to be clear my point wasn't: don't use the router service, it was: don't mock the router service. Mocking leads to extremely brittle tests and often times to tests that pass when "reality is broken". The router service is perfectly capable of being used in these types of test, it can be used directly.

**Comment by bartocc** [comment] 2019-07-02 12:31
Since discussing the mocking of the router service is a bit off topic here, I've opened https://discuss.emberjs.com/t/to-stub-or-not-to-stub-the-router-service-in-integration-tests/16742 for the discussion to continue

**Comment by NullVoxPopuli** [comment] 2019-07-26 15:29
I made a helper: 

https://github.com/emberjs/ember-test-helpers/pull/689/files

:-/

**Comment by adong** [comment] 2020-02-28 08:19
> > Still seeing this issue when mocking the service:router inside integrations tests.
> 
> Don't do that 😈. Seriously though, why would you want to mock the router?

Because sometimes we need to mock the `currentRouteName`

```
this.owner.unregister('service:router');
this.owner.register('service:router', routerServiceMock);

const routerServiceMock = Service.extend({
  currentRoute: {
    name: 'someRouteName'
  }
});
```

Not sure if there are better ways

**Comment by KroneckerDeIta** [comment] 2020-11-12 11:09
> Just to be clear my point wasn't: don't use the router service, it was: don't mock the router service. Mocking leads to extremely brittle tests and often times to tests that pass when "reality is broken". The router service is perfectly capable of being used in these types of test, it can be used directly.

I know I am a little late to respond but I wanted to respond to this point. Mocks are very useful in certain types of tests because most of the time we are writing unit tests, which should only be testing the functionality of the unit in question, and mocking calls to methods in services (for example) is very useful if they have complicated functionality we don't want to handle in that particular test. In this particular thread we are talking about mocks in acceptance tests which is more of a grey area. If you really want to mock a method in the router I would suggest you use a mocking library like sinon to just stub the one method, rather than stubbing the whole service.

I am happy to be corrected on this though, I am always looking for the best ways of testing code.

**Comment by williamhaley** [comment] 2021-02-18 17:50
Just to give some context about the dev experience from my perspective...

I found that following the [canonical guides](https://guides.emberjs.com/release/testing/testing-components/) on "how to mock a service in a component" wasn't working. I struggled with the issue for a few hours. I came here, and found there was no meaningful answer.

The docs/guides imply any service can be mocked to help test components, but that is not reality. I too want to stub basic behavior like `router:currentRoute.name`, and it appears I can't

**Comment by KroneckerDeIta** [comment] 2021-02-18 18:14
> Just to give some context about the dev experience from my perspective...
> 
> I found that following the [canonical guides](https://guides.emberjs.com/release/testing/testing-components/) on "how to mock a service in a component" wasn't working. I struggled with the issue for a few hours. I came here, and found there was no meaningful answer.
> 
> The docs/guides imply any service can be mocked to help test components, but that is not reality. I too want to stub basic behavior like `router:currentRoute.name`, and it appears I can't

Can you not just use Sinon to create a stub object or create an Ember object in the test and overwrite the router service in the component (passed in as an argument) or use Sinon to stub currentRoute in the router and set name on the stub?

**Comment by williamhaley** [comment] 2021-02-18 18:22
> Can you not just use Sinon to create a stub object or create an Ember object in the test and overwrite the router service in the component (passed in as an argument) or use Sinon to stub currentRoute in the router and set name on the stub?

For sure. And the workaround above to use `unregister` works fine too.

But I guess my broader point is that the `Testing Components` article on ember.com has this text...

>  In cases where components have dependencies on Ember services, it is possible to stub these dependencies for rendering tests. You stub Ember services by using the built-in register() function to register your stub service in place of the default.

...which isn't always accurate. The taught Ember way for stubbing services has the gotchas described here by myself and others.

I should've amended my comment above from "..and it appears we can't" to "...it appears we can't as described by the docs".

Sorry to tack on to an old issue in a deprecated repo, but this is my first Google result for "ember stub service not working" so I thought it was worth calling it out here.

**Comment by KroneckerDeIta** [comment] 2021-02-18 18:27
You are able to submit pull requests to update the ember guides and they do get approved quite quickly. You could add a warning to the guides saying that certain services, like router, should/can not be mocked.

**Comment by NullVoxPopuli** [comment] 2021-02-18 18:32
The router can be mocked. At least in < 3.20.

The big stipulation around registering services in general is that if they are accessed before registration (such as in an initializer either in app or addon), the registration will silently fail.

The best DX I can think of for that is to add an assertion that alerts you to that behavior/situation.

That said, I'm also in the camp of 'it's not a good idea to stub things like the router's - it leads to over stubbing and tests that are overly tied to implementation details, making refactors annoying

**Comment by williamhaley** [comment] 2021-02-18 18:39
https://github.com/ember-learn/guides-source/pull/1635
